# Generated by Django 4.2.7 on 2023-11-14 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20200118_2214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_profile',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
